### ISSUE TITLE
ActiveSupport::Concern::MultipleIncludedBlocks Error with Puma

### ISSUE THREAD

**Issue by KentaKogumasaka** [pinzolo/redmine_persist_wfmt#20]
We implement Puma for web service with Redmine 4.1.  Installing the plugin fails because of `ActiveSupport::Concern::MultipleIncludedBlocks` error.  Does anyone have a good idea how to deal with?

> redmine           | * Restarting...
redmine           | Puma starting in single mode...
redmine           | * Version 4.3.5 (ruby 2.6.6-p146), codename: Mysterious Traveller
redmine           | * Min threads: 8, max threads: 8
redmine           | * Environment: production
redmine           | W, [2020-06-23T06:30:50.355566 #15]  WARN -- : Creating scope :sorted. Overwriting existing method Group.sorted.
redmine           | W, [2020-06-23T06:30:50.395894 #15]  WARN -- : Creating scope :sorted. Overwriting existing method User.sorted.
redmine           | W, [2020-06-23T06:30:50.682857 #15]  WARN -- : Creating scope :system. Overwriting existing method Enumeration.system.
redmine           | ! Unable to load application: ActiveSupport::Concern::MultipleIncludedBlocks: Cannot define multiple 'included' blocks for a Concern
redmine           | /usr/local/bundle/gems/activesupport-5.2.4.2/lib/active_support/concern.rb:130:in `included': Cannot define multiple 'included' blocks for a Concern (ActiveSupport::Concern::MultipleIncludedBlocks)
redmine           |     from /usr/src/redmine/plugins/redmine_persist_wfmt/lib/patches/controller/application_controller_patch.rb:8:in `<module:ApplicationControllerPatch>'
redmine           |     from /usr/src/redmine/plugins/redmine_persist_wfmt/lib/patches/controller/application_controller_patch.rb:5:in `<module:Pwfmt>'
redmine           |     from /usr/src/redmine/plugins/redmine_persist_wfmt/lib/patches/controller/application_controller_patch.rb:1:in `<top (required)>'
redmine           |     from /usr/local/bundle/gems/activesupport-5.2.4.2/lib/active_support/dependencies.rb:291:in `require'
redmine           |     from /usr/local/bundle/gems/activesupport-5.2.4.2/lib/active_support/dependencies.rb:291:in `block in require'
redmine           |     from /usr/local/bundle/gems/activesupport-5.2.4.2/lib/active_support/dependencies.rb:257:in `load_dependency'
redmine           |     from /usr/local/bundle/gems/activesupport-5.2.4.2/lib/active_support/dependencies.rb:291:in `require'
redmine           |     from /usr/local/bundle/gems/activesupport-5.2.4.2/lib/active_support/dependencies.rb:378:in `block in require_or_load'
redmine           |     from /usr/local/bundle/gems/activesupport-5.2.4.2/lib/active_support/dependencies.rb:37:in `block in load_interlock'
redmine           |     from /usr/local/bundle/gems/activesupport-5.2.4.2/lib/active_support/dependencies/interlock.rb:14:in `block in loading'
redmine           |     from /usr/local/bundle/gems/activesupport-5.2.4.2/lib/active_support/concurrency/share_lock.rb:151:in `exclusive'
redmine           |     from /usr/local/bundle/gems/activesupport-5.2.4.2/lib/active_support/dependencies/interlock.rb:13:in `loading'
redmine           |     from /usr/local/bundle/gems/activesupport-5.2.4.2/lib/active_support/dependencies.rb:37:in `load_interlock'
redmine           |     from /usr/local/bundle/gems/activesupport-5.2.4.2/lib/active_support/dependencies.rb:356:in `require_or_load'
redmine           |     from /usr/local/bundle/gems/activesupport-5.2.4.2/lib/active_support/dependencies.rb:334:in `depend_on'
redmine           |     from /usr/local/bundle/gems/activesupport-5.2.4.2/lib/active_support/dependencies.rb:246:in `require_dependency'
redmine           |     from /usr/local/bundle/gems/railties-5.2.4.2/lib/rails/engine.rb:478:in `block (2 levels) in eager_load!'
redmine           |     from /usr/local/bundle/gems/railties-5.2.4.2/lib/rails/engine.rb:477:in `each'
redmine           |     from /usr/local/bundle/gems/railties-5.2.4.2/lib/rails/engine.rb:477:in `block in eager_load!'
redmine           |     from /usr/local/bundle/gems/railties-5.2.4.2/lib/rails/engine.rb:475:in `each'
redmine           |     from /usr/local/bundle/gems/railties-5.2.4.2/lib/rails/engine.rb:475:in `eager_load!'
redmine           |     from /usr/local/bundle/gems/railties-5.2.4.2/lib/rails/engine.rb:356:in `eager_load!'
redmine           |     from /usr/local/bundle/gems/railties-5.2.4.2/lib/rails/application/finisher.rb:69:in `each'
redmine           |     from /usr/local/bundle/gems/railties-5.2.4.2/lib/rails/application/finisher.rb:69:in `block in <module:Finisher>'
redmine           |     from /usr/local/bundle/gems/railties-5.2.4.2/lib/rails/initializable.rb:32:in `instance_exec'
redmine           |     from /usr/local/bundle/gems/railties-5.2.4.2/lib/rails/initializable.rb:32:in `run'
redmine           |     from /usr/local/bundle/gems/railties-5.2.4.2/lib/rails/initializable.rb:61:in `block in run_initializers'
redmine           |     from /usr/local/lib/ruby/2.6.0/tsort.rb:228:in `block in tsort_each'
redmine           |     from /usr/local/lib/ruby/2.6.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
redmine           |     from /usr/local/lib/ruby/2.6.0/tsort.rb:431:in `each_strongly_connected_component_from'
redmine           |     from /usr/local/lib/ruby/2.6.0/tsort.rb:349:in `block in each_strongly_connected_component'
redmine           |     from /usr/local/lib/ruby/2.6.0/tsort.rb:347:in `each'
redmine           |     from /usr/local/lib/ruby/2.6.0/tsort.rb:347:in `call'
redmine           |     from /usr/local/lib/ruby/2.6.0/tsort.rb:347:in `each_strongly_connected_component'
redmine           |     from /usr/local/lib/ruby/2.6.0/tsort.rb:226:in `tsort_each'
redmine           |     from /usr/local/lib/ruby/2.6.0/tsort.rb:205:in `tsort_each'
redmine           |     from /usr/local/bundle/gems/railties-5.2.4.2/lib/rails/initializable.rb:60:in `run_initializers'
redmine           |     from /usr/local/bundle/gems/railties-5.2.4.2/lib/rails/application.rb:361:in `initialize!'
redmine           |     from /usr/src/redmine/config/environment.rb:16:in `<top (required)>'
redmine           |     from /usr/local/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
redmine           |     from /usr/local/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
redmine           |     from config.ru:1:in `block in <main>'
redmine           |     from /usr/local/bundle/gems/rack-2.2.3/lib/rack/builder.rb:116:in `eval'
redmine           |     from /usr/local/bundle/gems/rack-2.2.3/lib/rack/builder.rb:116:in `new_from_string'
redmine           |     from /usr/local/bundle/gems/rack-2.2.3/lib/rack/builder.rb:105:in `load_file'
redmine           |     from /usr/local/bundle/gems/rack-2.2.3/lib/rack/builder.rb:66:in `parse_file'
redmine           |     from /usr/local/bundle/gems/puma-4.3.5/lib/puma/configuration.rb:321:in `load_rackup'
redmine           |     from /usr/local/bundle/gems/puma-4.3.5/lib/puma/configuration.rb:246:in `app'
redmine           |     from /usr/local/bundle/gems/puma-4.3.5/lib/puma/runner.rb:155:in `load_and_bind'
redmine           |     from /usr/local/bundle/gems/puma-4.3.5/lib/puma/single.rb:98:in `run'
redmine           |     from /usr/local/bundle/gems/puma-4.3.5/lib/puma/launcher.rb:172:in `run'
redmine           |     from /usr/local/bundle/gems/puma-4.3.5/lib/puma/cli.rb:80:in `run'
redmine           |     from /usr/local/bundle/gems/puma-4.3.5/bin/puma:10:in `<top (required)>'
redmine           |     from /usr/local/bundle/bin/puma:23:in `load'
redmine           |     from /usr/local/bundle/bin/puma:23:in `<main>'
redmine           | 2020/06/23 06:30:53.625535 [ERR] (cli) child process died with exit code 1

**Comment by sasaiyu** [comment]
I had the same situation and tried to dealt with the problem. Although I' m not Ruby engineer (actually it was just one week after I was happened this problem and at this time I had not known Ruby) and didn't confirm the  launch in the same environment, but I think our problem is the same  and my idea would help you who read this comment.

I explain the detail of my problem and idea in [my github](https://github.com/sasaiyu/bitnami-redmine) (it's Japanese. I'm sorry). In my conclusion, before launch,  you delete after the line 12 of `redmine_persist_wfmt/lib/pwfmt.rb` . Because, Redmine 5 works in Zeitwerk mode and auto-load this plugin But `redmine_persist_wfmt/lib/pmwft.rb` re-load after the line 12 and that causes the double definition of `ActiveSupport::Concern`. 

 I confrim to good work in [bitnami/redmine](https://hub.docker.com/r/bitnami/redmine) and image [5.0.5-debian-11-r15](https://hub.docker.com/layers/bitnami/redmine/5.0.5-debian-11-r15/images/sha256-556ece25bf13133f54ffb55b782d4977daadc4b1832834da3e41b4e7d3ae3537?context=explore).

I'm glad if my idea helps you.
